server:
  port: 8092
  servlet:
    context-path: /
    
# Spring
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yonghedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root   

     #配置视图解析器
  #thymeleaf:
    #prefix: classpath:/webapp/pags/
    #suffix: .jsp
    
    #配置mvc页面
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp 
    
#mybatis: 
mybatis-plus:
     #配置mapper映射
  mapper-locations: classpath:/mybatis/mappers/*.xml
     #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
  
#添加日志输出
logging:
  level:
    com.tedu.dao: debug    
